/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!


goog.provide('proto.events.Event');
goog.provide('proto.events.Module');


/**
 * @enum {number}
 */
proto.events.Module = {
  INVALID_MODULE: 0,
  LOGIN: 100,
  SIGNUP: 101,
  FEED: 200,
  USER: 300,
  ORG: 301,
  USER_SETTINGS: 400,
  ORG_SETTINGS: 401,
  HUB: 500,
  HUB_TEAM: 501,
  HUB_SETTINGS: 600,
  HUB_SETTINGS_DESIGN: 601,
  HUB_SETTINGS_ADDONS: 602,
  HUB_SETTINGS_COLLECTIONS: 603,
  HUB_SETTINGS_EMBEDS: 604,
  HUB_SETTINGS_INTEGRATIONS: 605,
  HUB_SETTINGS_CTAS: 606,
  HUB_MANAGE_CONTENT: 700,
  HUB_NEWSLETTERS: 701,
  HUB_NEWSLETTERS_TEMPLATES: 702,
  HUB_NEWSLETTERS_MAILING_LISTS: 703,
  HUB_ANALYTICS: 704,
  EMAIL: 800
};

/**
 * @enum {number}
 */
proto.events.Event = {
  INVALID_EVENT: 0,
  CREATE: 1,
  VIEW: 2,
  UPDATE: 3,
  DELETE: 4,
  OPEN: 5,
  PUBLISH: 15,
  UNPUBLISH: 16,
  SCHEDULE: 17,
  JOIN: 6,
  LEAVE: 7,
  INVITE: 8,
  ACCEPT: 9,
  REJECT: 10,
  REQUEST_ACCESS: 11,
  GRANT_ACCESS: 12,
  DENY_ACCESS: 13,
  LOGIN_FAIL: 101,
  LOGIN_OK: 102,
  POST_LIKE: 200,
  POST_UNLIKE: 201,
  POST_SHARE: 202,
  POST_AMPLIFY: 203,
  POST_COMMENT: 204,
  POST_COMMENT_DELETE: 205,
  EMAIL_PENDING_ACCEPTED: 300,
  EMAIL_PENDING_DELAYED_UNKNOWN: 301,
  EMAIL_PENDING_DELAYED_GRAYLIST: 302,
  EMAIL_PENDING_DELAYED_RATE_LIMIT: 303,
  EMAIL_PENDING_MAILBOX_FULL: 304,
  EMAIL_PENDING_SERVER_ERROR: 305,
  EMAIL_REJECTED_UNSUBSCRIBED: 310,
  EMAIL_REJECTED_SPAM_COMPLAINT: 311,
  EMAIL_REJECTED_INVALID_RECIPIENT: 312,
  EMAIL_REJECTED_HARD_BOUNCED: 313,
  EMAIL_BOUNCED_UNKNOWN: 320,
  EMAIL_BOUNCED_DROPPED: 321,
  EMAIL_BOUNCED_INVALID_RECIPIENT: 322,
  EMAIL_BOUNCED_SPAM_SENDER: 323,
  EMAIL_BOUNCED_SPAM_CONTENT: 324,
  EMAIL_BOUNCED_TOO_LARGE: 325,
  EMAIL_BOUNCED_BLOCKED: 326,
  EMAIL_DELIVERED: 330,
  EMAIL_DELIVERED_OPENED: 331,
  EMAIL_DELIVERED_CLICKED: 332,
  EMAIL_DELIVERED_SHARED: 333,
  EMAIL_DELIVERED_UNSUBSCRIBED: 334,
  EMAIL_DELIVERED_SPAM_COMPLAINT: 335
};

