/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!


goog.provide('proto.events.Event');
goog.provide('proto.events.Module');


/**
 * @enum {number}
 */
proto.events.Module = {
  INVALID_MODULE: 0,
  LOGIN: 100,
  SIGNUP: 101,
  USER_PROFILE: 200,
  USER_SETTINGS: 201,
  ORG_PROFILE: 300,
  ORG_SETTINGS: 301,
  HUB: 400,
  HUB_STREAM: 401,
  HUB_SPOTLIGHT: 402,
  HUB_SETTINGS_PROFILE: 403,
  HUB_SETTINGS_DOMAIN: 413,
  HUB_SETTINGS_ADVANCED: 414,
  HUB_TEAM: 404,
  HUB_TEAM_COLLABORATORS: 410,
  HUB_TEAM_MEMBERS: 411,
  HUB_TEAM_INVITES: 412,
  HUB_FEEDS: 405,
  HUB_MANAGE_CONTENT: 406,
  HUB_NEWSLETTERS: 407,
  HUB_ANALYTICS: 408,
  HUB_EMBEDS: 409,
  HUB_SETTINGS_DESIGN_COVER: 415,
  HUB_SETTINGS_DESIGN_HEADER: 416,
  HUB_SETTINGS_DESIGN_TEXT: 417,
  HUB_SETTINGS_ADDONS: 418,
  HUB_SETTINGS_COLLECTIONS: 419,
  HUB_SETTINGS_CTAS: 420,
  FEED: 500,
  EXTERNAL: 600,
  EMAIL: 601
};

/**
 * @enum {number}
 */
proto.events.Event = {
  INVALID_EVENT: 0,
  CREATE: 1,
  VIEW: 2,
  UPDATE: 3,
  DELETE: 4,
  OPEN: 5,
  PUBLISH: 15,
  UNPUBLISH: 16,
  SCHEDULE: 17,
  JOIN: 6,
  LEAVE: 7,
  INVITE: 8,
  ACCEPT: 9,
  REJECT: 10,
  REQUEST_ACCESS: 11,
  GRANT_ACCESS: 12,
  DENY_ACCESS: 13,
  CHANGE_ROLE: 14,
  PASSWORD_LOGIN_FAIL: 101,
  PASSWORD_LOGIN_OK: 102,
  SSO_LOGIN_FAIL: 103,
  SSO_LOGIN_OK: 104,
  SOCIAL_LOGIN_FAIL: 105,
  SOCIAL_LOGIN_OK: 106,
  POST_LIKE: 200,
  POST_UNLIKE: 201,
  POST_SHARE: 202,
  POST_AMPLIFY: 203,
  POST_COMMENT: 204,
  POST_COMMENT_DELETE: 205,
  EMAIL_PENDING_ACCEPTED: 300,
  EMAIL_PENDING_DELAYED_UNKNOWN: 301,
  EMAIL_PENDING_DELAYED_GRAYLIST: 302,
  EMAIL_PENDING_DELAYED_RATE_LIMIT: 303,
  EMAIL_PENDING_MAILBOX_FULL: 304,
  EMAIL_PENDING_SERVER_ERROR: 305,
  EMAIL_REJECTED_UNSUBSCRIBED: 310,
  EMAIL_REJECTED_SPAM_COMPLAINT: 311,
  EMAIL_REJECTED_INVALID_RECIPIENT: 312,
  EMAIL_REJECTED_HARD_BOUNCED: 313,
  EMAIL_BOUNCED_UNKNOWN: 320,
  EMAIL_BOUNCED_DROPPED: 321,
  EMAIL_BOUNCED_INVALID_RECIPIENT: 322,
  EMAIL_BOUNCED_SPAM_SENDER: 323,
  EMAIL_BOUNCED_SPAM_CONTENT: 324,
  EMAIL_BOUNCED_TOO_LARGE: 325,
  EMAIL_BOUNCED_BLOCKED: 326,
  EMAIL_DELIVERED: 330,
  EMAIL_DELIVERED_OPENED: 331,
  EMAIL_DELIVERED_CLICKED: 332,
  EMAIL_DELIVERED_SHARED: 333,
  EMAIL_DELIVERED_UNSUBSCRIBED: 334,
  EMAIL_DELIVERED_SPAM_COMPLAINT: 335
};

